.PHONY: clean All

All:
	@echo "----------Building project:[ phantom_slam_arm - Debug ]----------"
	@cd "/home/anthony/PHANTOM/Demo/Robotics/phantom_slam/arm" && "$(MAKE)" -f  "phantom_slam_arm.mk"
clean:
	@echo "----------Cleaning project:[ phantom_slam_arm - Debug ]----------"
	@cd "/home/anthony/PHANTOM/Demo/Robotics/phantom_slam/arm" && "$(MAKE)" -f  "phantom_slam_arm.mk" clean
